about:
  home: http://github.com/idigbio/idigbio-media-appliance
  license: MIT License
  summary: iDigBio Media Appliance
build:
  entry_points:
  - idigbio_media_appliance=idigbio_media_appliance.__main__:main
package:
  name: idigbio-media-appliance
  version: 2.5.0
requirements:
  build:
  - python
  - setuptools
  - flask
  - flask-restful
  - flask-sqlalchemy
  - alembic
  - easygui
  - appdirs
  - gevent
  - idigbio
  - unicodecsv
  - idigbio
  run:
  - python
  - flask
  - flask-restful
  - flask-sqlalchemy
  - alembic
  - easygui
  - appdirs
  - gevent
  - idigbio
  - unicodecsv
  - idigbio
source:
  fn: idigbio-media-appliance-2.5.0.tar.gz
  md5: 240512f9b589f3d775973d5bcb676789
  url: https://pypi.python.org/packages/4c/68/4dd27674aab4c27066ce6019dd7e4bb1e553ba1842fe3abc5bfefa066ee0/idigbio-media-appliance-2.5.0.tar.gz
test:
  commands:
  - idigbio_media_appliance --help
  imports:
  - idigbio_media_appliance
  - idigbio_media_appliance.api
  - idigbio_media_appliance.lib
  - idigbio_media_appliance.models
  - idigbio_media_appliance.tests
  - idigbio_media_appliance.views
