about:
  home: git://github.com/idigbio/idigbio-media-appliance
  license: MIT License
  summary: iDigBio Media Appliance
build:
  entry_points:
  - idigbio_media_appliance=idigbio_media_appliance.__main__:main
package:
  name: idigbio-media-appliance
  version: 2.0.8
requirements:
  build:
  - python
  - setuptools
  - flask
  - flask-restful
  - flask-sqlalchemy
  - alembic
  - gevent
  - easygui
  - appdirs
  - unicodecsv
  - idigbio
  run:
  - python
  - flask
  - flask-restful
  - flask-sqlalchemy
  - alembic
  - gevent
  - easygui
  - appdirs
  - unicodecsv
  - idigbio
source:
  fn: idigbio-media-appliance-2.0.8.tar.gz
  md5: 7902ffe9b8ee07c7421a65bbe031cd04
  url: https://pypi.python.org/packages/d0/63/667cdf449af4215b7d4801d8c9d99e85f0fa66e8a41fcb4c2bd9414f9c32/idigbio-media-appliance-2.0.8.tar.gz
test:
  commands: null
  imports:
  - idigbio_media_appliance
  - idigbio_media_appliance.api
  - idigbio_media_appliance.lib
  - idigbio_media_appliance.models
  - idigbio_media_appliance.tests
  - idigbio_media_appliance.views
