about:
  home: http://github.com/idigbio/idigbio-media-appliance
  license: MIT License
  summary: iDigBio Media Appliance
build:
  entry_points:
  - idigbio_media_appliance=idigbio_media_appliance.__main__:main
package:
  name: idigbio-media-appliance
  version: 2.5.2
requirements:
  build:
  - python
  - setuptools
  - flask
  - flask-restful
  - flask-sqlalchemy
  - alembic
  - easygui
  - appdirs
  - gevent
  - idigbio
  - unicodecsv
  - idigbio
  run:
  - python
  - flask
  - flask-restful
  - flask-sqlalchemy
  - alembic
  - easygui
  - appdirs
  - gevent
  - idigbio
  - unicodecsv
  - idigbio
source:
  fn: idigbio-media-appliance-2.5.2.tar.gz
  md5: 8707ca16e733707092895e47d129d7f1
  url: https://pypi.python.org/packages/ea/18/d2a0a431a027ceb52e3e435b3ad4f2039456071d9f13b69a1d981fa03899/idigbio-media-appliance-2.5.2.tar.gz
test:
  commands:
  - idigbio_media_appliance --help
  imports:
  - idigbio_media_appliance
  - idigbio_media_appliance.api
  - idigbio_media_appliance.lib
  - idigbio_media_appliance.models
  - idigbio_media_appliance.tests
  - idigbio_media_appliance.views
