about:
  home: git://github.com/idigbio/idigbio-media-appliance
  license: MIT License
  summary: iDigBio Media Appliance
build:
  entry_points:
  - idigbio_media_appliance=idigbio_media_appliance.__main__:main
package:
  name: idigbio-media-appliance
  version: 2.2.2
requirements:
  build:
  - python
  - setuptools
  - flask
  - flask-restful
  - flask-sqlalchemy
  - alembic
  - gevent
  - easygui
  - appdirs
  - unicodecsv
  - idigbio
  run:
  - python
  - flask
  - flask-restful
  - flask-sqlalchemy
  - alembic
  - gevent
  - easygui
  - appdirs
  - unicodecsv
  - idigbio
source:
  fn: idigbio-media-appliance-2.2.2.tar.gz
  md5: 0dc49faafd307355662cd74e24356698
  url: https://pypi.python.org/packages/39/de/d599d9e15268491724a7aa4191c753e6f48102570438c9e99a3142fd7d6b/idigbio-media-appliance-2.2.2.tar.gz
test:
  commands: null
  imports:
  - idigbio_media_appliance
  - idigbio_media_appliance.api
  - idigbio_media_appliance.lib
  - idigbio_media_appliance.models
  - idigbio_media_appliance.tests
  - idigbio_media_appliance.views
