about:
  home: git://github.com/idigbio/idigbio-media-appliance
  license: MIT License
  summary: iDigBio Media Appliance
build:
  entry_points:
  - idigbio_media_appliance=idigbio_media_appliance.__main__:main
package:
  name: idigbio-media-appliance
  version: 2.4.0
requirements:
  build:
  - python
  - setuptools
  - flask
  - flask-restful
  - flask-sqlalchemy
  - alembic
  - gevent
  - easygui
  - appdirs
  - unicodecsv
  - idigbio
  run:
  - python
  - flask
  - flask-restful
  - flask-sqlalchemy
  - alembic
  - gevent
  - easygui
  - appdirs
  - unicodecsv
  - idigbio
source:
  fn: idigbio-media-appliance-2.4.0.tar.gz
  md5: dc7b0cd09b3aa137444ff60a9a094af7
  url: https://pypi.python.org/packages/37/7b/5cd1fb6fc48d1ca0b2c03f982d1d7861eba0ed899a3301f8c06d70f18279/idigbio-media-appliance-2.4.0.tar.gz
test:
  commands: null
  imports:
  - idigbio_media_appliance
  - idigbio_media_appliance.api
  - idigbio_media_appliance.lib
  - idigbio_media_appliance.models
  - idigbio_media_appliance.tests
  - idigbio_media_appliance.views
