package:
  name: idigbio-media-appliance
  version: "2.4.0"

source:
  fn: idigbio-media-appliance-2.4.0.tar.gz
  url: https://pypi.python.org/packages/37/7b/5cd1fb6fc48d1ca0b2c03f982d1d7861eba0ed899a3301f8c06d70f18279/idigbio-media-appliance-2.4.0.tar.gz
  md5: dc7b0cd09b3aa137444ff60a9a094af7
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - idigbio-media-appliance = idigbio-media-appliance:main
    #
    # Would create an entry point called idigbio-media-appliance that calls idigbio-media-appliance.main()

    - idigbio_media_appliance=idigbio_media_appliance.__main__:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - flask
    - flask-restful
    - flask-sqlalchemy
    - alembic
    - easygui
    - appdirs
    - gevent
    - idigbio
    - unicodecsv
    - idigbio

  run:
    - python
    - flask
    - flask-restful
    - flask-sqlalchemy
    - alembic
    - easygui
    - appdirs
    - gevent
    - idigbio
    - unicodecsv
    - idigbio

test:
  # Python imports
  imports:
    - idigbio_media_appliance
    - idigbio_media_appliance.api
    - idigbio_media_appliance.lib
    - idigbio_media_appliance.models
    - idigbio_media_appliance.tests
    - idigbio_media_appliance.views

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - idigbio_media_appliance --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/idigbio/idigbio-media-appliance
  license: MIT License
  summary: 'iDigBio Media Appliance'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
