about:
  home: http://github.com/idigbio/idigbio-media-appliance
  license: MIT License
  summary: iDigBio Media Appliance
build:
  entry_points:
  - idigbio_media_appliance=idigbio_media_appliance.__main__:main
package:
  name: idigbio-media-appliance
  version: 2.4.3
requirements:
  build:
  - python
  - setuptools
  - flask
  - flask-restful
  - flask-sqlalchemy
  - alembic
  - easygui
  - appdirs
  - gevent
  - idigbio
  - unicodecsv
  - idigbio
  run:
  - python
  - flask
  - flask-restful
  - flask-sqlalchemy
  - alembic
  - easygui
  - appdirs
  - gevent
  - idigbio
  - unicodecsv
  - idigbio
source:
  fn: idigbio-media-appliance-2.4.3.tar.gz
  md5: dcb5431ee4873334c0f004b02483b41c
  url: https://pypi.python.org/packages/03/c7/a03ab34a928c287c0c67d15b4935087100e9c8e27ac714f3c3400da8c52b/idigbio-media-appliance-2.4.3.tar.gz
test:
  commands:
  - idigbio_media_appliance --help
  imports:
  - idigbio_media_appliance
  - idigbio_media_appliance.api
  - idigbio_media_appliance.lib
  - idigbio_media_appliance.models
  - idigbio_media_appliance.tests
  - idigbio_media_appliance.views
